# dockerfile für backend -> excalidraw
FROM python:3.11.5-alpine3.18
WORKDIR /
ENV FLASK_APP=backend/server.py
ENV FLASK_RUN_HOST=0.0.0.0
RUN apk add --no-cache gcc musl-dev linux-headers
RUN pip install flask flask_cors
EXPOSE 8888
COPY . .
CMD ["flask", "run"]
